version: '3'

services:

  app:
    container_name: youtube-api-postgres
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      PORT: 3000
      DB_CONN: "postgres://user:password@db:5432/db?sslmode=disable"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: youtube_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
      TZ: 'UTC'
      PGTZ: 'UTC'